### ISSUE TITLE
Running in Python 3.6 and 2.7 causes contextlib error

### ISSUE THREAD

**Issue by varunnair18** [google-research/uda#50]
Hello @qizhex ,

I tried running the image directory (CIFAR10) of UDA using the latest repository and ran into the following error: 

![image](https://user-images.githubusercontent.com/15525087/65914767-ffa7c100-e39f-11e9-9489-eb3a22c37e80.png)

Changing my environment into Python 2.7 avoids this error, but instead produces a different one. I thought it would be more relevant to post this issue instead because more members of the community are using python 3.6+ than 2.7. 

The data was successfully downloaded using the provided scripts, but training on my GPU does not work. What would you recommend doing?

**Comment by qizhex** [comment]
What error do you see when you use python2.7? I am not working on adapting to python3.6 but would appreciate it if someone could help adapt it.

**Comment by varunnair18** [comment]
@qizhex this is the error I get when I run it on python 2.7: 
![image](https://user-images.githubusercontent.com/15525087/66213326-8654ea80-e68d-11e9-8855-fca9959f450b.png)

It also seems that training is running on the CPU instead of the GPU, I'm unsure why that would be happening as other tensorflow models that I've run are detecting it.

**Comment by qizhex** [comment]
It seems like an API error. Are you using TF 1.13? It is actually using GPU. TPUEstimator will print "Running train on CPU" if you are not using TPU.

**Comment by varunnair18** [comment]
I updated to TF 1.13.1, but now I receive the original error that I posted, so the same contextlib error appears in both 3.6 and 2.7. 

![image](https://user-images.githubusercontent.com/15525087/66227654-98de1c80-e6ab-11e9-8c9d-7bdb580d0430.png)

**Comment by qizhex** [comment]
I think you are still using python3 instead of python2. When I used python 3, I got the same error:
```
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import contextlib
>>> contextlib.nested()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'contextlib' has no attribute 'nested'
```

I don't have this problem when I switched to python2. 
```
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import contextlib
>>> contextlib.nested()
<contextlib.GeneratorContextManager object at 0x7f634b563bd0>
```

**Comment by varunnair18** [comment]
Thanks for pointing that out! I updated my cudalibtoolkit to the correct version and fixed the issue in python 2.7.

I've also done some research into the error for python 3.6 and changed `build_model()` in image/main.py (line 221) that now makes the repository compatible with python 3.6. 


```
scopes = setup_arg_scopes(is_training)

  try:
      from contextlib import nested
  except ImportError:
      from contextlib import ExitStack, contextmanager

      @contextmanager
      def nested(*contexts):
          with ExitStack() as stack:
              for ctx in contexts:
                  stack.enter_context(ctx)
              yield contexts

  with nested(*scopes):
    if hparams.model_name == "pyramid_net":
      logits = build_shake_drop_model(
          inputs, num_classes, is_training)
    elif hparams.model_name == "wrn":
      logits = build_wrn_model(
          inputs, num_classes, hparams.wrn_size, update_bn)
    elif hparams.model_name == "shake_shake":
      logits = build_shake_shake_model(
          inputs, num_classes, hparams, is_training)

  return logits
```

I will submit this change as a pull request so that the repository can work for both python 2.7 and 3.6+ users.
